version: '3'

server:
  command: "php -d opcache.enable_cli=true -d opcache.jit_buffer_size=32M public/index.php"
  env: 
    - APP_ENV=${APP_ENV:-production}
    - APP_DEBUG=${APP_DEBUG:-false}

http:
  address: 0.0.0.0:8080
  middleware: ["headers", "static", "gzip"]
  static:
    dir: "public"
    forbid: [".php"]
  headers:
    response:
      "X-Powered-By": "PHP 8.4"
  pool:
    num_workers: 4
    max_jobs: 1000
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: production
  level: warn
  encoding: json
  output: stderr

reload:
  interval: 1s
  patterns: [".php"]
  services:
    http:
      recursive: true
      ignore: ["vendor"]

telemetry:
  address: 127.0.0.1:2112
  prometheus:
    path: /metrics

health:
  address: 0.0.0.0:2114
