<?php
declare(strict_types=1);

namespace Infinri\Seo\Service;

use Infinri\Seo\Model\UrlRewrite;
use Infinri\Seo\Model\Repository\UrlRewriteRepository;
use Infinri\Core\Helper\Logger;

/**
 * URL Rewrite Generator Service
 * 
 * Automatically generates URL rewrites for entities
 */
class UrlRewriteGenerator
{
    public function __construct(
        private readonly UrlRewriteRepository $urlRewriteRepository
    ) {
    }

    /**
     * Generate URL rewrite for CMS page
     *
     * @param int $pageId
     * @param string $urlKey
     * @param string $storeId
     * @return UrlRewrite
     */
    public function generateForCmsPage(int $pageId, string $urlKey, string $storeId = 'default'): UrlRewrite
    {
        // Check if URL rewrite already exists for this page
        $existing = $this->urlRewriteRepository->getByEntity('cms_page', $pageId, $storeId);

        if ($existing) {
            // Update existing rewrite if URL key changed
            if ($existing->getRequestPath() !== $urlKey) {
                Logger::info('Updating URL rewrite for CMS page', [
                    'page_id' => $pageId,
                    'old_url' => $existing->getRequestPath(),
                    'new_url' => $urlKey
                ]);

                $existing->setRequestPath($urlKey);
                $existing->setTargetPath("cms/page/view?key={$urlKey}");
                return $this->urlRewriteRepository->save($existing);
            }

            return $existing;
        }

        // Create new URL rewrite
        Logger::info('Creating URL rewrite for CMS page', [
            'page_id' => $pageId,
            'url_key' => $urlKey
        ]);

        $urlRewrite = new UrlRewrite();
        $urlRewrite->setRequestPath($urlKey);
        $urlRewrite->setTargetPath("cms/page/view?key={$urlKey}");
        $urlRewrite->setEntityType('cms_page');
        $urlRewrite->setEntityId($pageId);
        $urlRewrite->setRedirectType(0); // No redirect
        $urlRewrite->setStoreId($storeId);
        $urlRewrite->setIsAutogenerated(true);

        return $this->urlRewriteRepository->save($urlRewrite);
    }

    /**
     * Delete URL rewrite for CMS page
     *
     * @param int $pageId
     * @return bool
     */
    public function deleteForCmsPage(int $pageId): bool
    {
        Logger::info('Deleting URL rewrite for CMS page', ['page_id' => $pageId]);
        return $this->urlRewriteRepository->deleteByEntity('cms_page', $pageId);
    }

    /**
     * Regenerate all CMS page URL rewrites
     *
     * @param array $pages Array of page data
     * @return int Number of URL rewrites generated
     */
    public function regenerateAllCmsPages(array $pages): int
    {
        $count = 0;

        foreach ($pages as $page) {
            if (isset($page['page_id'], $page['url_key'])) {
                try {
                    $this->generateForCmsPage(
                        (int)$page['page_id'],
                        $page['url_key']
                    );
                    $count++;
                } catch (\Exception $e) {
                    Logger::error('Failed to generate URL rewrite', [
                        'page_id' => $page['page_id'],
                        'error' => $e->getMessage()
                    ]);
                }
            }
        }

        Logger::info('Regenerated CMS page URL rewrites', ['count' => $count]);
        return $count;
    }
}
