<?php
declare(strict_types=1);

namespace Infinri\Seo\Model;

use Infinri\Core\Model\AbstractModel;
use Infinri\Core\Model\ResourceModel\AbstractResource;
use Infinri\Seo\Model\ResourceModel\UrlRewrite as UrlRewriteResource;

/**
 * URL Rewrite Model
 * 
 * Represents a URL rewrite rule that maps friendly URLs to internal paths
 */
class UrlRewrite extends AbstractModel
{
    /**
     * Constructor
     */
    public function __construct(
        protected readonly UrlRewriteResource $resource,
        array $data = []
    ) {
        parent::__construct($data);
    }

    /**
     * Get resource model
     */
    protected function getResource(): AbstractResource
    {
        return $this->resource;
    }
    /**
     * Get URL Rewrite ID
     */
    public function getUrlRewriteId(): ?int
    {
        $value = $this->getData('url_rewrite_id');
        return $value !== null ? (int)$value : null;
    }

    /**
     * Set URL Rewrite ID
     */
    public function setUrlRewriteId(int $urlRewriteId): self
    {
        return $this->setData('url_rewrite_id', $urlRewriteId);
    }

    /**
     * Get Request Path (the friendly URL)
     */
    public function getRequestPath(): string
    {
        return (string)$this->getData('request_path');
    }

    /**
     * Set Request Path
     */
    public function setRequestPath(string $requestPath): self
    {
        return $this->setData('request_path', $requestPath);
    }

    /**
     * Get Target Path (the internal path)
     */
    public function getTargetPath(): string
    {
        return (string)$this->getData('target_path');
    }

    /**
     * Set Target Path
     */
    public function setTargetPath(string $targetPath): self
    {
        return $this->setData('target_path', $targetPath);
    }

    /**
     * Get Entity Type (cms_page, category, etc.)
     */
    public function getEntityType(): string
    {
        return (string)$this->getData('entity_type');
    }

    /**
     * Set Entity Type
     */
    public function setEntityType(string $entityType): self
    {
        return $this->setData('entity_type', $entityType);
    }

    /**
     * Get Entity ID
     */
    public function getEntityId(): ?int
    {
        $value = $this->getData('entity_id');
        return $value !== null ? (int)$value : null;
    }

    /**
     * Set Entity ID
     */
    public function setEntityId(?int $entityId): self
    {
        return $this->setData('entity_id', $entityId);
    }

    /**
     * Get Redirect Type (0=no redirect, 301, 302)
     */
    public function getRedirectType(): int
    {
        return (int)$this->getData('redirect_type');
    }

    /**
     * Set Redirect Type
     */
    public function setRedirectType(int $redirectType): self
    {
        return $this->setData('redirect_type', $redirectType);
    }

    /**
     * Get Store ID
     */
    public function getStoreId(): string
    {
        return (string)$this->getData('store_id');
    }

    /**
     * Set Store ID
     */
    public function setStoreId(string $storeId): self
    {
        return $this->setData('store_id', $storeId);
    }

    /**
     * Is Auto-generated
     */
    public function isAutogenerated(): bool
    {
        $value = $this->getData('is_autogenerated');
        return $value === true || $value === 1 || $value === '1' || $value === 't';
    }

    /**
     * Set Auto-generated
     */
    public function setIsAutogenerated(bool $isAutogenerated): self
    {
        return $this->setData('is_autogenerated', $isAutogenerated);
    }
}
