<?php
declare(strict_types=1);

namespace Infinri\Seo\Setup\Patch\Data;

use Infinri\Core\Setup\Patch\DataPatchInterface;
use Infinri\Core\Helper\Logger;
use PDO;

/**
 * Generate URL Rewrites for Existing CMS Pages
 */
class GenerateUrlRewrites implements DataPatchInterface
{
    private PDO $connection;

    public function __construct(PDO $connection)
    {
        $this->connection = $connection;
    }

    /**
     * {@inheritdoc}
     */
    public function apply(): void
    {
        Logger::info('Generating URL rewrites for existing CMS pages');

        // Get all CMS pages from database
        $stmt = $this->connection->query(
            "SELECT page_id, url_key FROM cms_page WHERE is_active = '1'"
        );
        $pages = $stmt->fetchAll(PDO::FETCH_ASSOC);
        $count = 0;

        foreach ($pages as $page) {
            try {
                // Check if URL rewrite already exists
                $checkStmt = $this->connection->prepare(
                    "SELECT url_rewrite_id FROM url_rewrite 
                     WHERE entity_type = 'cms_page' 
                     AND entity_id = :entity_id"
                );
                $checkStmt->execute(['entity_id' => $page['page_id']]);
                
                if ($checkStmt->fetchColumn()) {
                    continue; // Skip if already exists
                }

                // Insert URL rewrite
                $insertStmt = $this->connection->prepare(
                    "INSERT INTO url_rewrite 
                     (request_path, target_path, entity_type, entity_id, redirect_type, store_id, is_autogenerated) 
                     VALUES (:request_path, :target_path, :entity_type, :entity_id, :redirect_type, :store_id, :is_autogenerated)"
                );
                
                $insertStmt->execute([
                    'request_path' => $page['url_key'],
                    'target_path' => 'cms/page/view?key=' . $page['url_key'],
                    'entity_type' => 'cms_page',
                    'entity_id' => $page['page_id'],
                    'redirect_type' => 0,
                    'store_id' => 'default',
                    'is_autogenerated' => true
                ]);
                
                $count++;
            } catch (\Exception $e) {
                Logger::error('Failed to generate URL rewrite for page', [
                    'page_id' => $page['page_id'],
                    'url_key' => $page['url_key'],
                    'error' => $e->getMessage()
                ]);
            }
        }

        Logger::info('Generated URL rewrites', ['count' => $count]);
    }

    /**
     * {@inheritdoc}
     */
    public static function getDependencies(): array
    {
        return [
            \Infinri\Cms\Setup\Patch\Data\InstallDefaultCmsPages::class
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function getAliases(): array
    {
        return [];
    }
}
